In [113]:
import pandas as pd
import numpy as np
from glob import glob
import pickle
from collections import Counter

In [114]:
annot_file_lst = glob('./KEMDy20/annotation/*.csv')
annot_file_lst = sorted(annot_file_lst)
annot_file_lst[:3]

['./KEMDy20/annotation/Sess01_eval.csv',
 './KEMDy20/annotation/Sess02_eval.csv',
 './KEMDy20/annotation/Sess03_eval.csv']

In [115]:
# session 1만 해보기
# for i in annot_file_lst:
#     file_lst = pd.read_csv(i, skiprows = 1)[' .1']
import re

for i in range(len(annot_file_lst)):
    # print(annot_file_lst[i])
    if i == 0:
        annot_data = pd.read_csv(annot_file_lst[i], skiprows = 1)
    else:
        annot_data = pd.concat([annot_data, pd.read_csv(annot_file_lst[i], skiprows = 1)], axis= 0)
annot_data.rename(columns = {' .1': 'segment_id'}, inplace= True)
annot_data

,,start,end,segment_id,Emotion,Valence,Arousal,Emotion.1,Valence.1,Arousal.1,...,Arousal.7,Emotion.8,Valence.8,Arousal.8,Emotion.9,Valence.9,Arousal.9,Emotion.10,Valence.10,Arousal.10
0,1,3.578390,11.637391,Sess01_script01_User002M_001,neutral,3.4,2.9,neutral,3,3,...,3,neutral,4,3,neutral,3,3,neutral,3,3
1,2,11.637391,23.334393,Sess01_script01_User002M_002,neutral,3.1,2.9,neutral,3,3,...,3,neutral,4,3,neutral,3,3,neutral,3,3
2,3,23.334393,31.558392,Sess01_script01_User002M_003,neutral,3.1,3.0,neutral,3,3,...,3,neutral,4,3,neutral,3,3,neutral,3,3
3,4,31.558392,42.970390,Sess01_script01_User002M_004,neutral,3.7,3.1,neutral,4,3,...,3,neutral,4,4,neutral,3,3,neutral,4,3
4,5,42.777290,44.863290,Sess01_script01_User001F_001,neutral,3.8,2.8,happy,5,2,...,2,neutral,4,3,neutral,3,3,happy,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,494,289.449980,294.943000,Sess40_script06_User079F_043,neutral,3.0,3.5,neutral,3,4,...,4,neutral,3,4,neutral,3,4,neutral,3,4
494,495,294.943000,297.598000,Sess40_script06_User079F_044,neutral,2.9,3.1,neutral,3,2,...,3,neutral,3,3,neutral,3,4,neutral,2,4
495,496,297.598000,304.171000,Sess40_script06_User079F_045,neutral,2.6,3.6,neutral,2,3,...,4,neutral,2,4,fear,2,4,neutral,3,4
496,497,304.171000,306.863000,Sess40_script06_User079F_046,neutral,2.7,3.3,disgust,2,3,...,4,neutral,2,3,neutral,2,4,surprise,3,4
497,498,306.863000,309.107000,Sess40_script06_User079F_047,neutral,2.9,3.4,disgust,2,4,...,4,neutral,3,3,neutral,3,4,neutral,3,4

In [116]:
with open('./model/data/paradeigma_ts_data_preprocessing.pkl', 'rb') as f:
    ts_dataset_by_session = pickle.load(f)
ts_dataset_by_session[1]

,segment_id,emotion,valence,arousal,eda,temp,ibi
0,Sess01_script01_User002M_001,neutral,3.4,2.9,"[-0.06791500000000017, -0.110201, -0.025627999...","[34.81, 34.81, 34.81, 34.79, 34.79, 34.79, 34....",NaN
1,Sess01_script01_User002M_002,neutral,3.1,2.9,"[0.006407000000000274, -0.021784000000000248, ...","[34.79, 34.79, 34.79, 34.77, 34.77, 34.77, 34....","[0.65625, 0.609375, 0.609375]"
2,Sess01_script01_User002M_003,neutral,3.1,3,"[0.07944700000000005, 0.05125599999999997, 0.0...","[34.75, 34.75, 34.75, 34.75, 34.79, 34.79, 34....",NaN
3,Sess01_script01_User002M_004,neutral,3.7,3.1,"[0.0038439999999999586, -0.03331699999999982, ...","[34.77, 34.77, 34.77, 34.77, 34.77, 34.77, 34....",NaN
4,Sess01_script01_User001F_001,neutral,3.8,2.8,"[0.1241910000000006, 0.09474499999999964, 0.03...","[34.55, 34.55, 34.55, 34.55, 34.55, 34.55, 34....","[0.640625, 0.640625, 0.578125]"
...,...,...,...,...,...,...,...
306,Sess01_script06_User001F_016,neutral,3.3,3.5,"[0.006400999999999435, -0.010241999999999862, ...","[34.43, 34.43, 34.43, 34.43, 34.43, 34.41, 34....",NaN
307,Sess01_script06_User002M_041,neutral,3.3,3.1,"[0.0038450000000000983, -0.007689000000000057,...","[36.05, 36.05, 36.05, 36.05, 36.03, 36.03, 36....",NaN
308,Sess01_script06_User002M_042,neutral,3,2.9,"[0.06279299999999965, 0.019222000000000072, -0...","[36.07, 36.07, 36.07, 36.07, 36.05, 36.05, 36....",NaN
309,Sess01_script06_User002M_043,neutral,3,2.7,"[-0.010251999999999928, -0.0038450000000000983...","[36.07, 36.05, 36.05, 36.05, 36.05]",NaN
310,Sess01_script06_User001F_017,neutral,3,3.4,"[-0.01408300000000029, -0.025605999999999796, ...","[34.41, 34.43, 34.43, 34.43, 34.43, 34.45, 34....",NaN

In [117]:
for i in range(1,40+1):
    if i == 1:
        ts_dataset_flatten = ts_dataset_by_session[i].loc[:,['segment_id','eda','temp']]
    else:
        ts_dataset_flatten = pd.concat([ts_dataset_flatten, ts_dataset_by_session[i].loc[:,['segment_id','eda','temp']]], axis= 0)
ts_dataset_flatten = ts_dataset_flatten.reset_index()
ts_dataset_flatten

,index,segment_id,eda,temp
0,0,Sess01_script01_User002M_001,"[-0.06791500000000017, -0.110201, -0.025627999...","[34.81, 34.81, 34.81, 34.79, 34.79, 34.79, 34...."
1,1,Sess01_script01_User002M_002,"[0.006407000000000274, -0.021784000000000248, ...","[34.79, 34.79, 34.79, 34.77, 34.77, 34.77, 34...."
2,2,Sess01_script01_User002M_003,"[0.07944700000000005, 0.05125599999999997, 0.0...","[34.75, 34.75, 34.75, 34.75, 34.79, 34.79, 34...."
3,3,Sess01_script01_User002M_004,"[0.0038439999999999586, -0.03331699999999982, ...","[34.77, 34.77, 34.77, 34.77, 34.77, 34.77, 34...."
4,4,Sess01_script01_User001F_001,"[0.1241910000000006, 0.09474499999999964, 0.03...","[34.55, 34.55, 34.55, 34.55, 34.55, 34.55, 34...."
...,...,...,...,...
13457,493,Sess40_script06_User079F_043,"[-0.023063999999999973, -0.02050200000000002, ...","[35.07, 35.07, 35.07, 35.07, 35.05, 35.05, 35...."
13458,494,Sess40_script06_User079F_044,"[-0.0064070000000000515, -0.005125000000000046...","[35.05, 35.05, 35.07, 35.07, 35.07, 35.07, 35...."
13459,495,Sess40_script06_User079F_045,"[-0.007688000000000028, -0.002561999999999953,...","[35.05, 35.05, 35.05, 35.05, 35.05, 35.05, 35...."
13460,496,Sess40_script06_User079F_046,"[-0.0064069999999999405, -0.003844000000000069...","[35.05, 35.07, 35.07, 35.07, 35.07, 35.07, 35...."
13461,497,Sess40_script06_User079F_047,"[-0.002562999999999982, 0.0012819999999998943,...","[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35...."

In [118]:
import math
def add_padding(pd_series, length = 50):
    if isinstance(pd_series, float):
        if math.isnan(pd_series):
            return np.zeros(10)
    if len(pd_series) < length:
        pd_series = np.concatenate([pd_series, np.zeros(length - len(pd_series))])
        return pd_series
    elif len(pd_series) == length:
        return pd_series
    elif len(pd_series) > length:
        pd_series = pd_series[:length]
        return pd_series

In [121]:
padded_eda_data = map(add_padding , ts_dataset_flatten['eda'])
ts_dataset_flatten['eda'] = list(padded_eda_data)
padded_temp_data = map(add_padding , ts_dataset_flatten['temp'])
ts_dataset_flatten['temp'] = list(padded_temp_data)

# check
ts_dataset_flatten['eda'][0], ts_dataset_flatten['temp'][0]

(array([-0.067915, -0.110201, -0.025628, -0.007688, -0.02691 , -0.011533,
        -0.125578, -0.049974, -0.045439, -0.01794 ,  0.084573,  0.060227,
         0.057663,  0.053819,  0.039724,  0.023065, -0.012814, -0.053819,
        -0.079447, -0.121734, -0.065352,  0.002563,  0.006407,  0.006407,
        -0.044849,  0.044849,  0.074322,  0.131985,  0.029472,  0.012814,
         0.010251,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ]),
 array([34.81, 34.81, 34.81, 34.79, 34.79, 34.79, 34.79, 34.81, 34.81,
        34.81, 34.81, 34.79, 34.79, 34.79, 34.79, 34.81, 34.81, 34.81,
        34.81, 34.79, 34.79, 34.79, 34.79, 34.79, 34.79, 34.79, 34.79,
        34.79, 34.79, 34.79, 34.79, 34.79,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ]))

In [122]:
ts_dataset = pd.merge(annot_data, ts_dataset_flatten, on='segment_id', how='outer')
len(ts_dataset['temp'][0]),len(ts_dataset['eda'][0])

(50, 50)

In [124]:
# 참고: https://stackoverflow.com/questions/27275236/how-to-select-all-columns-whose-names-start-with-x-in-a-pandas-dataframe
filter_col = [col for col in ts_dataset.columns if col.startswith('Emotion.')]
filter_col
Counter(ts_dataset[filter_col].iloc[10])

Counter({'happy': 4, 'neutral': 6})

In [125]:
annot_target = []
for i in range(len(ts_dataset)):
    score_table = {'neutral': 0, 'happy': 0, 'surprise':0, 'disgust': 0, 'angry': 0, 'sad':0, 'fear': 0}
    i_of_tsdata = Counter(ts_dataset[filter_col].iloc[i])
    for emotion in i_of_tsdata.keys():
        score_table[emotion] += i_of_tsdata[emotion]
    annot_target.append(list(score_table.values()))
annot_target[:3]

[[10, 0, 0, 0, 0, 0, 0], [10, 0, 0, 0, 0, 0, 0], [10, 0, 0, 0, 0, 0, 0]]

In [126]:
ts_dataset['new_emotion'] = annot_target
ts_dataset

,,start,end,segment_id,Emotion,Valence,Arousal,Emotion.1,Valence.1,Arousal.1,...,Emotion.9,Valence.9,Arousal.9,Emotion.10,Valence.10,Arousal.10,index,eda,temp,new_emotion
0,1,3.578390,11.637391,Sess01_script01_User002M_001,neutral,3.4,2.9,neutral,3,3,...,neutral,3,3,neutral,3,3,0,"[-0.06791500000000017, -0.110201, -0.025627999...","[34.81, 34.81, 34.81, 34.79, 34.79, 34.79, 34....","[10, 0, 0, 0, 0, 0, 0]"
1,2,11.637391,23.334393,Sess01_script01_User002M_002,neutral,3.1,2.9,neutral,3,3,...,neutral,3,3,neutral,3,3,1,"[0.006407000000000274, -0.021784000000000248, ...","[34.79, 34.79, 34.79, 34.77, 34.77, 34.77, 34....","[10, 0, 0, 0, 0, 0, 0]"
2,3,23.334393,31.558392,Sess01_script01_User002M_003,neutral,3.1,3.0,neutral,3,3,...,neutral,3,3,neutral,3,3,2,"[0.07944700000000005, 0.05125599999999997, 0.0...","[34.75, 34.75, 34.75, 34.75, 34.79, 34.79, 34....","[10, 0, 0, 0, 0, 0, 0]"
3,4,31.558392,42.970390,Sess01_script01_User002M_004,neutral,3.7,3.1,neutral,4,3,...,neutral,3,3,neutral,4,3,3,"[0.0038439999999999586, -0.03331699999999982, ...","[34.77, 34.77, 34.77, 34.77, 34.77, 34.77, 34....","[9, 1, 0, 0, 0, 0, 0]"
4,5,42.777290,44.863290,Sess01_script01_User001F_001,neutral,3.8,2.8,happy,5,2,...,neutral,3,3,happy,4,3,4,"[0.1241910000000006, 0.09474499999999964, 0.03...","[34.55, 34.55, 34.55, 34.55, 34.55, 34.55, 34....","[6, 4, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13457,494,289.449980,294.943000,Sess40_script06_User079F_043,neutral,3.0,3.5,neutral,3,4,...,neutral,3,4,neutral,3,4,493,"[-0.023063999999999973, -0.02050200000000002, ...","[35.07, 35.07, 35.07, 35.07, 35.05, 35.05, 35....","[10, 0, 0, 0, 0, 0, 0]"
13458,495,294.943000,297.598000,Sess40_script06_User079F_044,neutral,2.9,3.1,neutral,3,2,...,neutral,3,4,neutral,2,4,494,"[-0.0064070000000000515, -0.005125000000000046...","[35.05, 35.05, 35.07, 35.07, 35.07, 35.07, 35....","[10, 0, 0, 0, 0, 0, 0]"
13459,496,297.598000,304.171000,Sess40_script06_User079F_045,neutral,2.6,3.6,neutral,2,3,...,fear,2,4,neutral,3,4,495,"[-0.007688000000000028, -0.002561999999999953,...","[35.05, 35.05, 35.05, 35.05, 35.05, 35.05, 35....","[9, 0, 0, 0, 0, 0, 1]"
13460,497,304.171000,306.863000,Sess40_script06_User079F_046,neutral,2.7,3.3,disgust,2,3,...,neutral,2,4,surprise,3,4,496,"[-0.0064069999999999405, -0.003844000000000069...","[35.05, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[8, 0, 1, 1, 0, 0, 0]"
13461,498,306.863000,309.107000,Sess40_script06_User079F_047,neutral,2.9,3.4,disgust,2,4,...,neutral,3,4,neutral,3,4,497,"[-0.002562999999999982, 0.0012819999999998943,...","[35.07, 35.07, 35.07, 35.07, 35.07, 35.07, 35....","[9, 0, 0, 1, 0, 0, 0]"

In [127]:
with open('./model/data/lou_ts_dataset.pkl', 'wb') as f:
    pickle.dump(ts_dataset, f, pickle.HIGHEST_PROTOCOL)